# Generated by Django 2.2.12 on 2021-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='_status',
            field=models.SmallIntegerField(default=1, verbose_name='状态'),
        ),
    ]
