# Generated by Django 2.2.12 on 2021-04-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_host__status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='_status',
            new_name='status',
        ),
    ]
