# Generated by Django 2.2.12 on 2021-04-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('asset', '0003_auto_20210425_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='状态'),
        ),
    ]
