# Generated by Django 2.2.12 on 2021-04-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20210425_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(default=1, help_text='0:禁用；1：启用', verbose_name='状态'),
        ),
    ]
