# Generated by Django 2.2.12 on 2021-05-07 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='剧本名称')),
                ('content', models.TextField(verbose_name='剧本内容')),
                ('version', models.CharField(default='', max_length=64, verbose_name='版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, utils.model.ModelMixin),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='任务名称')),
                ('inventory', models.CharField(max_length=256, verbose_name='主机清单')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('pb', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='task.Playbook')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, utils.model.ModelMixin),
        ),
    ]
